name: 'Example ci'
on: [push] # pull-request, fork
# on:
#   push:
#     branches:
#       - main
#       - 'releases/**'
#     branches-ignore:    
#       - 'releases/**-alpha'
jobs:
  analyze-flutter-project:
    runs-on: ubuntu-latest
    # if: "!contains(github.event.head_commit.message, 'skip analyze:')"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@1
        with: 
          java-version: 12.x
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter anlyze .
      - run: flutter format --set-exit-if-changed .